<?php

return [
    '' => 'site/index',
    'bassistenwitze' => 'joke/index',
    'blog' => 'blog/index',
    'blog/<id:[A-Za-z0-9-]+>' => 'blog/view',
    'tools/fingersaetze' => 'fingering/index',
    'tools/fingersaetze/<id:[A-Za-z0-9-]+>' => 'fingering/view',
    'tools/metronom' => 'tool/metronome',
    'glossar/reorder' => 'glossar/reorder',
    'glossar/<category>/<id>' => 'glossar/view',
    'glossar/<category>' => 'glossar/index',
    'glossar' => 'glossar/index',
    'impressum' => 'site/impressum',
    'katalog/hersteller' => 'manufacturer/index',
    'katalog/alben/index' => 'album/all',
    'katalog/alben/<id>' => 'album/view',
    'katalog/alben' => 'album/index',
    'katalog/<category>/index' => 'catalog/all',
    'katalog/<category>/<id>' => 'catalog/view',
    'katalog/<category>' => 'catalog/index',
    'katalog' => 'catalog/overview',
    'kleinanzeigen/' => 'advertisement/index',
    'kleinanzeigen/hinzufuegen' => 'advertisement/add',
    'kleinanzeigen/verwalten' => 'advertisement/manage',
    'kleinanzeigen/<id>' => 'advertisement/view',
    'advertisement/contact' => 'advertisement/contact',
    'advertisement/renew' => 'advertisement/renew',
    'advertisement/delete' => 'advertisement/delete',
    'advertisement/update' => 'advertisement/update',
    'kommentar/<name>-<id>' => 'comment/index',
    'kommentar/regeln' => 'comment/rules',
    'kontakt' => 'site/contact',
    'suche' => 'search/index',
    'tools' => 'tool/index',
    'tools/notenpapier' => 'tool/musicpaper',
    'websites/index' => 'website/all',
    'websites/<id:[A-Za-z0-9-]+>' => 'website/view',
    'websites' => 'website/index',
    'videos/<segment:isolierter-bass>/<id:[a-z0-9]+>' => 'youtube-playlist/view',
    'videos/<segment:isolierter-bass>' => 'youtube-playlist/index',
    'videos/<segment:klassische-musik>/<id:[a-z0-9]+>' => 'youtube-playlist/view',
    'videos/<segment:klassische-musik>' => 'youtube-playlist/index',
    'videos/<segment:solo-bass>/<id:[a-z0-9]+>' => 'youtube-playlist/view',
    'videos/<segment:solo-bass>' => 'youtube-playlist/index',
    'videos' => 'video/index',
    'videos/<eid:[A-Za-z0-9-]+>' => 'video/view',
    'sitemap' => 'sitemap/index',
    'sitemap/google' => 'sitemap/google',
    'zitate' => 'quote/index',
    'feed/rss' => 'feed/rss',
    'api/hits' => 'api/hits',
    'api/rate' => 'api/rate',
    'manufacturer/data' => 'manufacturer/data',
    'manufacturer/visit' => 'manufacturer/visit',
    'site/captcha' => 'site/captcha',
    'admin/<controller>/<action>' => 'admin/<controller>/<action>',
    'admin/<controller>' => 'admin/<controller>/index',
    'admin' => 'admin',
    'test' => 'site/test',
    'alpha-tab/editor' => 'alpha-tab/editor',
    [
        'pattern' => 'play/<uid:.+>',
        'route' => 'alpha-tab/view',
        'encodeParams' => false,
    ],
    [
        'pattern' => '<path:.+>',
        'route' => 'lesson/index',
        'encodeParams' => false,
    ],
];
