<?php

return [
    '' => 'homepage/index',
    'bassistenwitze' => 'joke/index',
    'blog' => 'blog/index',
    'blog/<id:[A-Za-z0-9-]+>' => 'blog/view',
    'tools/fingersaetze/inhaltsverzeichnis' => 'fingering/table-of-contents',
    'tools/fingersaetze/<category:(arpeggio|intervall|tonleiter)>' => 'fingering/index',
    'tools/fingersaetze/<id:[A-Za-z0-9-]+>' => 'fingering/view',
    'tools/fingersaetze' => 'fingering/index',
    'tools/metronom' => 'metronome/index',
    'tools/notenpapier' => 'music-paper/index',
    'glossar/reorder' => 'glossary/reorder',
    'glossar/<category>/<id>' => 'glossary/view',
    'glossar/<category>' => 'glossary/index',
    'glossar' => 'glossary/index',
    'katalog/alben/index' => 'album/all',
    'katalog/alben/<id>' => 'album/view',
    'katalog/alben' => 'album/index',
    'katalog/<category>/index' => 'catalog/all',
    'katalog/<category>/<id>' => 'catalog/view',
    'katalog/<category>' => 'catalog/index',
    'katalog' => 'catalog/overview',
    'kleinanzeigen/' => 'advertisement/index',
    'kleinanzeigen/hinzufuegen' => 'advertisement/add',
    'kleinanzeigen/verwalten' => 'advertisement/manage',
    'kleinanzeigen/kontaktieren' => 'advertisement/contact',
    'kleinanzeigen/erneuern' => 'advertisement/renew',
    'kleinanzeigen/loeschen' => 'advertisement/delete',
    'kleinanzeigen/aktualisieren' => 'advertisement/update',
    'kleinanzeigen/captcha' => 'advertisement/captcha',
    'kleinanzeigen/<id>' => 'advertisement/view',
    'kommentar/<name>-<id>' => 'comment/index',
    'kommentar/regeln' => 'comment/rules',
    'kontakt' => 'contact/index',
    'kontakt/captcha' => 'contact/captcha',
    'suche' => 'search/index',
    'videos/<segment:isolierter-bass>/<id:[a-z0-9]+>' => 'youtube/view',
    'videos/<segment:isolierter-bass>' => 'youtube/index',
    'videos/<segment:klassische-musik>/<id:[a-z0-9]+>' => 'youtube/view',
    'videos/<segment:klassische-musik>' => 'youtube/index',
    'videos/<segment:solo-bass>/<id:[a-z0-9]+>' => 'youtube/view',
    'videos/<segment:solo-bass>' => 'youtube/index',
    'videos' => 'video/index',
    'videos/<eid:[A-Za-z0-9-]+>' => 'video/view',
    'sitemap/google' => 'sitemap/google',
    'zitate' => 'quote/index',
    'feed/rss' => 'feed/rss',
    'api/hits' => 'api/hits',
    'api/rate' => 'api/rate',
    'admin/<controller>/<action>' => 'admin/<controller>/<action>',
    'admin/<controller>' => 'admin/<controller>/index',
    'admin' => 'admin',
    [
        'pattern' => 'quiz/<uid:.+>',
        'route' => 'quiz/view',
        'encodeParams' => false,
    ],
    'alpha-tab/debug' => 'alpha-tab/debug',
    'alpha-tab/editor' => 'alpha-tab/editor',
    [
        'pattern' => 'play/<uid:.+>',
        'route' => 'alpha-tab/view',
        'encodeParams' => false,
    ],
    [
        'pattern' => '<path:.+>',
        'route' => 'lesson/index',
        'encodeParams' => false,
    ],
];
